openapi: 3.0.0
info:
  version: 1.0.0
  title: hubme api
servers:
  - url: "http://localhost:8080"
paths:
  /user:
    $ref: "./paths/auth.yml#/user"
  /user/{uuid}:
    $ref: "./paths/auth.yml#/user_byUUID"
  /user/signup:
    $ref: "./paths/auth.yml#/user_signup"
  /user/signin:
    $ref: "./paths/auth.yml#/user_signin"